service: golem

provider:
  name: aws
  runtime: nodejs8.10

functions:
  geoindex:
    handler: handler.indexData
    events:
      - schedule: rate(30 days)

plugins:
  - serverless-offline
  - serverless-offline-scheduler
  - serverless-plugin-scripts

custom:
  scripts:
    commands:
      datasetdownload: node downloadDataset.js
    hooks:
      'deploy:finalize': sls invoke -f geoindex